### ISSUE TITLE
peer to peer code review 7th december 2021

### ISSUE THREAD

**Issue by mugishasam123** [OybekKayumov/portfolio-project#13]
congratulations on the work you did so far 💯 

- [ ] kindly remove commented codes to make your codebase beautiful
- [ ] I kindly suggest checking all necessary divs in your code and removing unnecessary ones 👍 
- [ ] please kindly use target links as your social media icons 🤙 
- [ ] have good luck in making suggested changes ❤️

**Comment by OybekKayumov** [comment]
Thanks for your suggestions!
